# Generated by Django 5.2.4 on 2025-07-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_campaign_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('income', models.PositiveIntegerField()),
                ('children', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('other_policy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('address', models.TextField()),
                ('job', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('rate', models.PositiveIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.campaign')),
            ],
        ),
    ]
